import { IFilm, FilmCategory } from "./types/films";

export const FILMS: IFilm[] = [
  {
    id: '1',
    title: 'Cidade de Deus',
    description: 'The story of two boys growing up in a violent neighborhood of Rio de Janeiro.',
    color: '#FFA500',
    category: FilmCategory.Crime,
    director: 'Fernando Meirelles, Kátia Lund',
    releaseYear: 2002,
    writer: 'Bráulio Mantovani (screenplay), Paulo Lins (novel)',
    synopsis: 'Spanning decades, the film follows two boys who choose divergent paths—one becomes a photographer, while the other a ruthless drug lord—amid the crime-ridden slums of Rio de Janeiro.',
  },
  {
    id: '2',
    title: 'Mad Max: Fury Road',
    description: 'In a post-apocalyptic wasteland, Max teams up with Furiosa to escape a tyrant.',
    color: '#1E3A8A',
    category: FilmCategory.Action,
    director: 'George Miller',
    releaseYear: 2015,
    writer: 'George Miller, Brendan McCarthy, Nick Lathouris',
    synopsis: 'Max and Furiosa join forces to escape a tyrannical ruler and cross a desert in a relentless, high-octane journey for survival and redemption.',
  },
  {
    id: '3',
    title: 'Pulp Fiction',
    description: 'A mix of crime stories interwoven with the lives of two mob hitmen and others.',
    color: '#8B0000',
    category: FilmCategory.Crime,
    director: 'Quentin Tarantino',
    releaseYear: 1994,
    writer: 'Quentin Tarantino, Roger Avary',
    synopsis: 'The film unfolds through several intertwined stories of crime, redemption, and dark humor, centering on two hitmen, a boxer, and a pair of robbers in a thrilling and stylized narrative.',
  },
  {
    id: '4',
    title: 'The Godfather',
    description: 'The aging patriarch of an organized crime dynasty transfers control to his son.',
    color: '#8B0000',
    category: FilmCategory.Crime,
    director: 'Francis Ford Coppola',
    releaseYear: 1972,
    writer: 'Mario Puzo (novel), Francis Ford Coppola (screenplay)',
    synopsis: 'The story chronicles the Corleone family, a powerful Mafia dynasty, as control passes from the aging Don Vito to his reluctant son Michael, changing both their lives forever.',
  },
  {
    id: '5',
    title: 'The Dark Knight',
    description: 'Batman faces off against the Joker, a criminal mastermind causing chaos in Gotham.',
    color: '#1E3A8A',
    category: FilmCategory.Action,
    director: 'Christopher Nolan',
    releaseYear: 2008,
    writer: 'Jonathan Nolan, Christopher Nolan (screenplay), David S. Goyer (story)',
    synopsis: 'In Gotham City, Batman battles the Joker, a criminal mastermind with a philosophy of chaos, while facing his own moral struggles as he tries to protect the people he loves.',
  },
  {
    id: '6',
    title: 'La La Land',
    description: 'A jazz musician and an aspiring actress fall in love while pursuing their dreams.',
    color: '#FF69B4',
    category: FilmCategory.Romance,
    director: 'Damien Chazelle',
    releaseYear: 2016,
    writer: 'Damien Chazelle',
    synopsis: 'Mia and Sebastian fall in love while chasing their artistic dreams in Los Angeles, only to face the challenges that their ambitions bring to their relationship.',
  },
  {
    id: '14',
    title: 'Titanic',
    description: 'A romance blossoms aboard the ill-fated R.M.S. Titanic.',
    color: '#FF69B4',
    category: FilmCategory.Romance,
    director: 'James Cameron',
    releaseYear: 1997,
    writer: 'James Cameron',
    synopsis: 'Rose and Jack, from different social backgrounds, find love aboard the Titanic, but their romance is threatened as the ship meets its tragic fate.',
  },
  {
    id: '15',
    title: 'The Matrix',
    description: 'A hacker discovers the reality he lives in is a simulated world controlled by machines.',
    color: '#1E3A8A',
    category: FilmCategory.Action,
    director: 'Lana Wachowski, Lilly Wachowski',
    releaseYear: 1999,
    writer: 'Lana Wachowski, Lilly Wachowski',
    synopsis: 'Neo, a computer hacker, learns that humanity is trapped in a simulated reality created by intelligent machines and must fulfill his destiny to free humankind.',
  },
];
